ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "parentalConsent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "parentEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "directoryRestriction" BOOLEAN NOT NULL DEFAULT false;
