import 'package:equatable/equatable.dart';

/// Roles that a message participant can have.
enum MessageRole { user, assistant, system }

/// A single message within an AI tutor conversation.
class ChatMessageEntity extends Equatable {
  final String id;
  final MessageRole role;
  final String content;
  final DateTime timestamp;

  const ChatMessageEntity({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
  });

  @override
  List<Object?> get props => [id, role, content, timestamp];

  factory ChatMessageEntity.fromJson(Map<String, dynamic> json) {
    return ChatMessageEntity(
      id: json['id'] as String? ?? '',
      role: _parseRole(json['role'] as String? ?? 'assistant'),
      content: json['content'] as String,
      timestamp: json['timestamp'] != null
          ? DateTime.parse(json['timestamp'] as String)
          : DateTime.now(),
    );
  }

  static MessageRole _parseRole(String raw) {
    switch (raw.toLowerCase()) {
      case 'user':
        return MessageRole.user;
      case 'system':
        return MessageRole.system;
      default:
        return MessageRole.assistant;
    }
  }
}

/// A flashcard generated by the AI.
class FlashcardEntity extends Equatable {
  final String question;
  final String answer;

  const FlashcardEntity({required this.question, required this.answer});

  @override
  List<Object?> get props => [question, answer];

  factory FlashcardEntity.fromJson(Map<String, dynamic> json) {
    return FlashcardEntity(
      question: json['question'] as String,
      answer: json['answer'] as String,
    );
  }
}
